### ISSUE TITLE
Setting ownership of /usr/local

### ISSUE THREAD

**Issue by matanox** [jekrb/iojs-update#1]
I get `> Setting ownership of /usr/local to USERNAME` as part of the run. Looking inside the script no surprise...

As we know, `usr/local/` is not unique to iojs...
Are you sure this is necessary?

**Comment by jakeburden** [comment]
Greetings @matanster!

Thank you for writing. As far as I'm aware, `/usr/local/` is the directory you are supposed to install binaries into. Setting ownership just means you could run binaries without `sudo`.

However, if there is something better I could be doing here I would be happy to see a recommendation.  Furthermore, if you want to take on the initiative to send a pull request, I'd be glad to see it through.

**Comment by matanox** [comment]
@jekrb I really appreciate the comment. As I don't feel sufficiently fluent about best practice for managing this directory's ownerships, I am not really in a position to suggest something very specific. The initial thought has been that it might possibly be more appropriate to only touch the iojs binaries, rather than the entire parent path. I might be just missing something about it. 

Having said that, again, thanks for publishing this, as it saved me a chunk of time for getting to the latest version!

**Comment by jakeburden** [comment]
I'll do some more research on this and keep your concerns in consideration. Also, I'll keep this issue open for some time to allow further conversation and input from others.
